_BASE_: "./bases/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/Misc/cascade_mask_rcnn_R_50_FPN_3x/144998488/model_final_480dd8.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 5
    NAME: CascadeROIHeads
    BATCH_SIZE_PER_IMAGE: 512 # Reduce this? Default 512
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
DATASETS:
  TRAIN: ("fashion_od_train",)
  TEST: ("fashion_od_val",)
SOLVER:
  IMS_PER_BATCH: 12 # Reduce this? Default 16
  BASE_LR: 0.0015
  STEPS: (6000, 8000)
  MAX_ITER: 9000 # 500 steps / epoch
  CHECKPOINT_PERIOD: 1000
TEST:
  # The period (in terms of steps) to evaluate the model during training.
  # Set to 0 to disable.
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: True
OUTPUT_DIR: "output"
