_BASE_: "./bases/Base-RCNN-FPN.yaml"
MODEL:
  # COCO weights
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 5
    BATCH_SIZE_PER_IMAGE: 512 # Reduce this? Default 512
  BACKBONE:
    FREEZE_AT: 5 # Default 2
DATASETS:
  TRAIN: ("fashion_od_train",)
  TEST: ("fashion_od_val",)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.2
SOLVER:
  IMS_PER_BATCH: 16 # Reduce this? Default 16
  BASE_LR: 0.001
  STEPS: (6000, 9000)
  MAX_ITER: 10000 # 500 steps / epoch
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TRAIN: (480, 504, 528, 552, 576, 600)
TEST:
  # The period (in terms of steps) to evaluate the model during training.
  # Set to 0 to disable.
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: True
OUTPUT_DIR: "output"
