_BASE_: "./bases/Base-RCNN-FPN.yaml"
MODEL:
  # resnet101
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_101_FPN_3x/137851257/model_final_f6e8b1.pkl"
  # resnet50
  # WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
    BATCH_SIZE_PER_IMAGE: 256 # Reduce this? Default 512
  BACKBONE:
    FREEZE_AT: 2 # Default 2
DATASETS:
  TRAIN: ("fashion_od_train",)
  TEST: ("fashion_od_val",)
# DATALOADER:
#   SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#   REPEAT_THRESHOLD: 0.2
SOLVER:
  IMS_PER_BATCH: 8 # Reduce this? Default 16
  BASE_LR: 0.0015
  STEPS: (12000, 16000)
  MAX_ITER: 18000 # 500 steps / epoch
  CHECKPOINT_PERIOD: 1000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TRAIN: (480, 504, 528, 552, 576, 600)
TEST:
  # The period (in terms of steps) to evaluate the model during training.
  # Set to 0 to disable.
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: True
OUTPUT_DIR: "output"
