_BASE_: "./bases/Base-RetinaNet.yaml"
MODEL:
  # COCO weights
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/retinanet_R_50_FPN_3x/190397829/model_final_5bd44e.pkl"
  RESNETS:
    DEPTH: 50
  RETINANET:
    NUM_CLASSES: 5
DATASETS:
  TRAIN: ("fashion_od_train",)
  TEST: ("fashion_od_val",)
SOLVER:
  IMS_PER_BATCH: 8 # Reduce this? Default 16
  BASE_LR: 0.01 # Note that RetinaNet uses a different default learning rate
  STEPS: (30000, 40000)
  MAX_ITER: 45000
TEST:
  # The period (in terms of steps) to evaluate the model during training.
  # Set to 0 to disable.
  EVAL_PERIOD: 2500
OUTPUT_DIR: "output"
