_BASE_: "./bases/Base-RetinaNet.yaml"
MODEL:
  # COCO weights
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/retinanet_R_50_FPN_3x/190397829/model_final_5bd44e.pkl"
  RESNETS:
    DEPTH: 50
  RETINANET:
    NUM_CLASSES: 5
  BACKBONE:
    FREEZE_AT: 5 # Default 2
DATASETS:
  TRAIN: ("fashion_od_train",)
  TEST: ("fashion_od_val",)
# DATALOADER:
#   NUM_WORKERS: 1
SOLVER:
  IMS_PER_BATCH: 16 # Reduce this? Default 16
  BASE_LR: 0.001 # Note that RetinaNet uses a different default learning rate
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000 # 500 steps / epoch
  STEPS: (6000, 9000)
  MAX_ITER: 10000 # 500 steps / epoch
  CHECKPOINT_PERIOD: 1000
TEST:
  # The period (in terms of steps) to evaluate the model during training.
  # Set to 0 to disable.
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output"
